Create Table project_3(
	ID serial Primary Key,
	Year VARCHAR NOT NULL,
	CAUSE_NAME VARCHAR NOT NULL,
	STATE VARCHAR NOT NULL,
	DEATHS VARCHAR NOT NULL,
	AADR VARCHAR NOT NULL,
	LEADING_CAUSES VARCHAR NOT NULL,
	Age_Adjusted_Death_Rate FLOAT NOT NULL
);

	